### ISSUE TITLE
Unable to access "admin" after install

### ISSUE THREAD

**Issue by bugsysop** [YunoHost-Apps/bludit_ynh#3]
I have just installed the package, but after install process (no errors message) I can’t acces the admin pannel: File not found.

Install logs: https://paste.yunohost.org/raw/osofazutaf

YunoHost 4.0.8 (stable).

**Comment by ericgaspar** [comment]
@bugsysop Are you installing in a sub-domain? have you tried installing in sub-folder? are you getting the same error?

Can you try to install from testing? `sudo yunohost app upgrade bludit -u https://github.com/YunoHost-Apps/bludit_ynh/tree/testing`

**Comment by bugsysop** [comment]
Installed in sub-domain a t root (no sub-folder).

The problem whas solved by installing the _testing_ branch.
